version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: secretaria_virtual
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=secretariaVirtual.settings

  celery:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: celery -A secretariaVirtual worker --loglevel=info --concurrency=4 -Q high,low --hostname=celery@%h
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=secretariaVirtual.settings

  celery_high:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: celery -A secretariaVirtual worker --loglevel=info --concurrency=2 -Q high --hostname=celery-high@%h
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=secretariaVirtual.settings

  celery_beat:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: celery -A secretariaVirtual beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=secretariaVirtual.settings

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
