# Generated by Django 4.2.25 on 2025-10-24 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Google OAuth access token', verbose_name='Access Token')),
                ('refresh_token', models.TextField(help_text='Google OAuth refresh token', verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(help_text='Token expiration date and time', verbose_name='Token Expires At')),
                ('calendar_id', models.CharField(default='primary', help_text='Google Calendar calendar ID', max_length=255, verbose_name='Calendar ID')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Whether Google Calendar synchronization is active', verbose_name='Sync Enabled')),
                ('sync_direction', models.CharField(choices=[('bidirectional', 'Bidirectional'), ('to_google', 'To Google'), ('from_google', 'From Google')], default='bidirectional', help_text='Event synchronization direction', max_length=20, verbose_name='Sync Direction')),
                ('notify_on_create', models.BooleanField(default=True, help_text='Send notification when creating event in Google Calendar', verbose_name='Notify on Create')),
                ('notify_on_update', models.BooleanField(default=True, help_text='Send notification when updating event in Google Calendar', verbose_name='Notify on Update')),
                ('notify_on_delete', models.BooleanField(default=True, help_text='Send notification when deleting event in Google Calendar', verbose_name='Notify on Delete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Date and time of last synchronization', null=True, verbose_name='Last Sync At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_integration', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Google Calendar Integration',
                'verbose_name_plural': 'Google Calendar Integrations',
                'db_table': 'google_calendar_integration',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Synchronization'), ('incremental', 'Incremental Synchronization'), ('manual', 'Manual Synchronization'), ('automatic', 'Automatic Synchronization')], max_length=20, verbose_name='Sync Type')),
                ('events_created', models.PositiveIntegerField(default=0, verbose_name='Events Created')),
                ('events_updated', models.PositiveIntegerField(default=0, verbose_name='Events Updated')),
                ('events_deleted', models.PositiveIntegerField(default=0, verbose_name='Events Deleted')),
                ('events_conflicted', models.PositiveIntegerField(default=0, verbose_name='Events in Conflict')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial')], max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='google_calendar.googlecalendarintegration', verbose_name='Integration')),
            ],
            options={
                'verbose_name': 'Google Calendar Sync Log',
                'verbose_name_plural': 'Google Calendar Sync Logs',
                'db_table': 'google_calendar_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(help_text='Event ID in Google Calendar', max_length=255, verbose_name='Google Event ID')),
                ('google_calendar_id', models.CharField(help_text='Calendar ID where the event was created', max_length=255, verbose_name='Google Calendar ID')),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='synced', max_length=20, verbose_name='Sync Status')),
                ('sync_error', models.TextField(blank=True, help_text='Error message in case of synchronization failure', null=True, verbose_name='Sync Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('last_sync_at', models.DateTimeField(auto_now=True, verbose_name='Last Sync At')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_event', to='appointments.appointment', verbose_name='Appointment')),
            ],
            options={
                'verbose_name': 'Google Calendar Event',
                'verbose_name_plural': 'Google Calendar Events',
                'db_table': 'google_calendar_event',
                'unique_together': {('google_event_id', 'google_calendar_id')},
            },
        ),
    ]
