# Generated by Django 4.2.25 on 2025-10-26 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Service Name")),
                ("name_pt_br", models.CharField(max_length=255, null=True, verbose_name="Service Name")),
                ("name_en", models.CharField(max_length=255, null=True, verbose_name="Service Name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("description_pt_br", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("description_en", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("duration_minutes", models.PositiveIntegerField(verbose_name="Duration (minutes)")),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Base Price")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active Service")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor/Provider",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recurrence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                        verbose_name="Day of Week",
                    ),
                ),
                ("day_of_month", models.IntegerField(blank=True, null=True, verbose_name="Day of Month")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="End Date")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active Recurrence")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor/Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurrence",
                "verbose_name_plural": "Recurrences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Block Title")),
                ("title_pt_br", models.CharField(max_length=255, null=True, verbose_name="Block Title")),
                ("title_en", models.CharField(max_length=255, null=True, verbose_name="Block Title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("description_pt_br", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("description_en", models.TextField(blank=True, null=True, verbose_name="Description")),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("holiday", "Holiday"),
                            ("maintenance", "Maintenance"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Block Type",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start Date/Time")),
                ("end_time", models.DateTimeField(verbose_name="End Date/Time")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active Block")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor/Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="Start Date/Time")),
                ("end_time", models.DateTimeField(verbose_name="End Date/Time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("notes_pt_br", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("notes_en", models.TextField(blank=True, null=True, verbose_name="Notes")),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Final Price"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments_as_actor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor/Provider",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments_as_client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="appointments.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-start_time"],
            },
        ),
    ]
